 nsn:
  connection:
   adress: antivps.pl
   type: ssh
   sshport: 22
   remoteport: 5432
   user: dbshepherd
   keepass: nsn
   passwd: dbshepherd
  databases:
   pgBase_test:
    name: dbshepherd_local
    user: dbshepherd
    passwd: dbshepherd
   pgBasex:
    keepass: test
    name: dbshepherd_local
    user: dbshepherd
    passwd: dbshepherd
 nsn_local:
  connection:
   adress: antivps.pl
   type: direct
   sshport: 22
   remoteport: 5432
   user: dbshepherd
   passwd: dbshepherd
  databases:
   baseHost:
    name: dbshepherd_host
    user: dbshepherd
    passwd: dbshepherd

 seba:
  connection:
   adress: 192.168.0.100
   type: ssh
   sshport: 22
   remoteport: 5432
   user: shepherd
   passwd: shepherd
  databases:
   db_dump:
    name: test
    user: test
    passwd: dbshepherd

 local:
  connection:
   adress: 127.0.0.1
   type: direct
   sshport: 22
   remoteport: 5432
   user: shepherd
   passwd: shepherd
  databases:
   local:
    name: postgres
    user: postgres
    passwd: root