 InvalidConnection:
  connection:
   adress: kax-gate.noip.me
   type: ssh
   sshport: 443
   remoteport: 5432
   passwd: nsn
  databases:
   pgBase_test:
    name: dbshepherd_local
    user: dbshepherd
    passwd: dbshepherd
   pgBasex:
    name: dbshepherd_local
    user: dbshepherd
    passwd: dbshepherd

 InvalidSSHPort:
  connection:
   adress: kax-gate.noip.me
   type: ssh
   sshport: 222
   remoteport: 443
   user: nsn
   passwd: nsn
  databases:
   pgBase_test:
    name: dbshepherd_local
    user: dbshepherd
    passwd: dbshepherd
   pgBasex:
    name: dbshepherd_local
    user: dbshepherd
    passwd: dbshepherd

 InvalidUsername:
  connection:
   adress: antivps.pl
   type: ssh
   sshport: 22
   remoteport: 5432
   user: shepherd
   passwd: nsn
  databases:
   pgBase_test:
    name: dbshepherd_local
    user: dbshepherd
    passwd: dbshepherd
   pgBasex:
    name: dbshepherd_local
    user: dbshepherd
    passwd: dbshepherd
 
 ShouldBeOK:
  connection:
   adress: antivps.pl
   type: ssh
   sshport: 22
   remoteport: 5432
   user: dbshepherd
   keepass: nsn
   passwd: dbshepherd
  databases:
   pgBase_test:
    name: dbshepherd_local
    user: dbshepherd
    passwd: dbshepherd
   pgBasex:
    name: dbshepherd_local
    user: dbshepherd
    passwd: dbshepherd

